services:
  nexu-api:
    image: nexu-api:latest
    volumes:
      - ./app:/var/www/html
      - php_data:/var/www/html/storage
    networks:
      - internal_network
    depends_on:
      - nexu-db

  nexu-db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    networks:
      - internal_network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    networks:
      - internal_network
      - public_network
    depends_on:
      - nexu-api

volumes:
  mysql_data:
  php_data:


networks:
  internal_network:
    driver: bridge
  public_network:
    driver: bridge
